language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-28.0.3
    - android-28
jdk:
  - oraclejdk8
before_install:
  - yes | sdkmanager "platforms;android-28"
script:
   - ./gradlew assembleDebug

deploy:
  provider: releases
  api_key:
    secure: "0e988470190dba23fa69cdffe54a2137fa40d09c"
  file: "app/build/outputs/apk/debug/app-debug.apk"
  file_glob: "true"
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: YHossam/TestCI

after_success:
  - sh set_tags.sh