language: android
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
jdk:
- oraclejdk8
before_install:
- yes | sdkmanager "platforms;android-28"
script:
- "./gradlew assembleDebug"
deploy:
  provider: releases
  api-key:
      secure: C9BN55/04oiUnrRJ0Vs9ozJVDBsALQgCOjpaYBxw7FNdh6zNgcl+65fqTgsf23a7JlM877r3yMNf6PZYkiBCiQE8T2dh7QZp4d4Loirh7o8GnIq/uLLcaHSkhIj3Eg97jcX9f6sHlaN8jZRbSOps1cdgdYZ92JuLDX+KpBrMv4FYvoW54KlxoEvmmch3Ot51fFFhX432silIzbRGpi0tMyW1PuOdEMdb8DytD3+Ix+iTzxNufOj3VFE3rNDNI1Mcvz3eTfNdUDFJ7tSkkHabg7RNAKLesfW6OdQbvdlCZ0cTQCleeIxgaPNOlSGdLfMinRZbe+gV/vhqWP+W1V595MDM5ZHxKNrdM2XxMxJwhE4IubSsG/M9NUBv1YvvYm0RMqM5/z2jWxfzXIx/X5r4XPy+aWImI1EUyKzH0Na0r3n1d2h+IpV72mb3DTVavykF7FypmruKsCfCCi7kXPK6XEgkCXoLlIrtRSrBwNjKePc7YWuGm29I00jN+VIRdTUmH2bC72C3A+nZlC4/hOuo3vlNl3YpWMe1kO8yRo5M9cIwfgaskGb7rR+8uvjmHWJVs8oLJ43LhyE1Ut+mpzuanoLk66ZXQYLe9w+yWVQx5nTFr8iXIK7p9KqddJ/5jBLky1YxMX/YG7IxkIk8Ms35iB1YpVx+YtEjxgIxu+WOACo=
  file: app/build/outputs/apk/debug/app-debug.apk
  file_glob: 'true'
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    branch: master
    repo: YHossam/TestCI
  after_success:
- sh set_tags.sh
