language: android
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
jdk:
- oraclejdk8
before_install:
- yes | sdkmanager "platforms;android-28"
script:
- "./gradlew assembleDebug"
deploy:
  provider: releases
  api_key:
    secure: R0oGje9WN5DH4pNhgrq2pWDuwlVu6XD6cozbCOZiS2s14t2EJWbf2bgeDKTe1xbTOq5dwNkxRqjXKp/7lgcfnwacJQHXb99obIuylI0yU46g0Rv4bo4qbfvAsWTlDKmmhy3OiisKKWnCy+Hcf/aD/EcHRpqjnUlr3xCi/TeecJYa5v9IrlIQ+xXdyeecmBRG7YH4B5B6Tw8sEhfVqLCQttjlHfZ5IkryNAf3TPraCVGLJI8RvoUYdkGY61wYSrgYbySmObWt3VVT3EWlo7SySnK3/JOUyFnRLj6NAtAiOCVpJxRatDeMPTyoDFQ4dDjcBClGo7fhKnn1X/d8IVkiMYlaiZiR4iB8fG7X9veCIT7pxyi6MmeWrzL6teNDN9hWVTOUJyKQ1j5YJyO0xoeNUurrh/Q19WaS1UGeXalAqeqySU7VIvCWNHAHUEQIp5rQIItm7JxFpG1xokj28n/oseHbIvKMRtKtSxI1gRNF4pYzbVd4YnX8dn0gXZmcY6z5YPwptTAA5lEyKMUXahw2ewOrsYRQVPLfEctNB8xGxVq4caWrJrIT020WxjId35dWNYDwn0G9JGlyLMm3jxaBPTlri947ZWoCTMq/w51Nlis/V4JcjjafBvr11/unlNUZEvlK5/saDw4BTBGzsqM0AaRWOIEqOdAzmPOpPgvm8s4=
  file: app/build/outputs/apk/debug/app-debug.apk
  file_glob: 'true'
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: YHossam/TestCI
after_success:
- sh set_tags.sh
env:
  global:
  - secure: R0oGje9WN5DH4pNhgrq2pWDuwlVu6XD6cozbCOZiS2s14t2EJWbf2bgeDKTe1xbTOq5dwNkxRqjXKp/7lgcfnwacJQHXb99obIuylI0yU46g0Rv4bo4qbfvAsWTlDKmmhy3OiisKKWnCy+Hcf/aD/EcHRpqjnUlr3xCi/TeecJYa5v9IrlIQ+xXdyeecmBRG7YH4B5B6Tw8sEhfVqLCQttjlHfZ5IkryNAf3TPraCVGLJI8RvoUYdkGY61wYSrgYbySmObWt3VVT3EWlo7SySnK3/JOUyFnRLj6NAtAiOCVpJxRatDeMPTyoDFQ4dDjcBClGo7fhKnn1X/d8IVkiMYlaiZiR4iB8fG7X9veCIT7pxyi6MmeWrzL6teNDN9hWVTOUJyKQ1j5YJyO0xoeNUurrh/Q19WaS1UGeXalAqeqySU7VIvCWNHAHUEQIp5rQIItm7JxFpG1xokj28n/oseHbIvKMRtKtSxI1gRNF4pYzbVd4YnX8dn0gXZmcY6z5YPwptTAA5lEyKMUXahw2ewOrsYRQVPLfEctNB8xGxVq4caWrJrIT020WxjId35dWNYDwn0G9JGlyLMm3jxaBPTlri947ZWoCTMq/w51Nlis/V4JcjjafBvr11/unlNUZEvlK5/saDw4BTBGzsqM0AaRWOIEqOdAzmPOpPgvm8s4=
