language: android
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
jdk:
- oraclejdk8
before_install:
- yes | sdkmanager "platforms;android-28"
script:
- "./gradlew assembleDebug"
deploy:
  provider: releases
  api_key:
    secure: bCuoQ6YvxD7Iw9mHny+kYaS4L1FLiYX7Shv+Duz6GTMepa2KzlN3BIqc5Twn1+i/+n4b56Sqs6xdpZJ2FNGK6yyXdtxgBVK7NPcPg1coj3CT7Cmbfi+lQYNFZppc+/aFR9UShaJ2ydFQJWKlxy64BMZbth+uvCuQKwXdDC8+pRZ++VOCFDYh3euYJhTM+Tba5vIkVXHXAjT1OBxkR9c0425fgCoRZ8z17wS6IlXME3lGSi1AcSc5OdgrPdL8N30a+kYlEvnAbr6C1O49cnbWbbpMyt0H5TcqU6zaDORhbDKqmO4I5nG451XqTGE/2glXB8UH2SRYhcQCRO7sGd8wmq9BCAud6outfFk6MCWCmXzMru0wYCdwWZtSbBWho7EzrGl3L2B+6WimgwP0y+ml2wJmtIZackMv6RHg93jLfYgiWPsMezvo4QuDkokMTGjAL/FKYZbbr5ialWLqnfAVpQI2BSUrZLQA9qbm7bhD9u8XX8Gmi95VXwTcZFTrOu9xDqvvz7xFAvamOY7zhtnDkRrc3lhRRsh3mRg96XsKWv8T4C2qKqRgg8YUOhcGdOiwg8tXMdNJRDqrfsV5F4zwGJL8f3Zf+jZRjN5EuQWugUiUlun6XCTAk0AOkoIp4S2z3oZF30FcnMfPay9zkIwuy9dZP6UmO9flu1B1gKjNTLQ=
  file: app/build/outputs/apk/debug/app-debug.apk
  file_glob: 'true'
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    branch: master
    repo: YHossam/TestCI
after_success:
- sh set_tags.sh
