language: android
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
jdk:
- oraclejdk8
before_install:
- yes | sdkmanager "platforms;android-28"
script:
- "./gradlew assembleDebug"
deploy:
  provider: releases
  api_key:
    secure: a3zNZexwA6A+g0Un9UR+7DXwPuHolzy+ipiA0InDICfv1Ti1K9m0Fu+gSz5RGb1Czm+3txkdqX7RUQh1nTbku7TxWub7e3vgM22eiVUims0Z03GQwyCjkTtYcwQU/VR1hsHWeLCRpGeinvUC1cgJ/pYiaPrIh9cjOALeshD8q+zcv8fI/Pp8Q1cV+zwcgz1RQeEHLGBblCfadwX3T2VT7QQ/UOW3ymifHwb1aPzXQgPN3zNrcOoCle8y7SLFZfMCz9RmROpNC4aPmTPT0fy4LpWFX+JEN9e3cK1RAEVBATCXirwpwPq2zV5AnU/Ly7yZlp104rL38hW7dfDp3fHPnLIDirQrOXUCc5sFgoJsQYOwbid715KIhfPWdaJxd6ueC3f61UFE0mFl7G9Evw4ZdpUDwVgxaSbpH9Od0aSspKMzEcZcLl4fpF4DvwclgiABMjO9cJYY0UGPrSVJE4j+M0xfZhqnWFZmP3Nc6mb4QxkZlMFgxGgV4Xm7bIrhlSUNEI6JL55OCxUwgGFLsrgUvfy928C9XQ41cNPZHpEXijsK8ADqo89/paYVbsZfEnIa/A0lSQbSCnpI0vZzf8KKWgbQ88cOmcMMJCVaFvj72d1Tvo0XWHv5gi76Rs+LRrwZPElyIdRkG1em3J8eEEKv9vm4164UnFmD+3x0JMH7MO0=
  file: app/build/outputs/apk/debug/app-debug.apk
  file_glob: 'true'
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: YHossam/TestCI

after_success:
- sh set_tags.sh

env:
  global:
    secure: a3zNZexwA6A+g0Un9UR+7DXwPuHolzy+ipiA0InDICfv1Ti1K9m0Fu+gSz5RGb1Czm+3txkdqX7RUQh1nTbku7TxWub7e3vgM22eiVUims0Z03GQwyCjkTtYcwQU/VR1hsHWeLCRpGeinvUC1cgJ/pYiaPrIh9cjOALeshD8q+zcv8fI/Pp8Q1cV+zwcgz1RQeEHLGBblCfadwX3T2VT7QQ/UOW3ymifHwb1aPzXQgPN3zNrcOoCle8y7SLFZfMCz9RmROpNC4aPmTPT0fy4LpWFX+JEN9e3cK1RAEVBATCXirwpwPq2zV5AnU/Ly7yZlp104rL38hW7dfDp3fHPnLIDirQrOXUCc5sFgoJsQYOwbid715KIhfPWdaJxd6ueC3f61UFE0mFl7G9Evw4ZdpUDwVgxaSbpH9Od0aSspKMzEcZcLl4fpF4DvwclgiABMjO9cJYY0UGPrSVJE4j+M0xfZhqnWFZmP3Nc6mb4QxkZlMFgxGgV4Xm7bIrhlSUNEI6JL55OCxUwgGFLsrgUvfy928C9XQ41cNPZHpEXijsK8ADqo89/paYVbsZfEnIa/A0lSQbSCnpI0vZzf8KKWgbQ88cOmcMMJCVaFvj72d1Tvo0XWHv5gi76Rs+LRrwZPElyIdRkG1em3J8eEEKv9vm4164UnFmD+3x0JMH7MO0=
